<?php

function translade_theme($existing, $type, $theme, $path) {
    // Base Page Theme
    $theme_templates = [];

    return $theme_templates;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function translade_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    // get saved content types from config
    $config = \Drupal::config('translade.settings');
    $content_types = $config->get('content_types') ?: [];

    foreach ($content_types as $content_type) {
        if ($form_id == 'node_' . $content_type . '_edit_form') {
            $form['#attached']['library'][] = 'translade/transladejs';
            $form['#attached']['library'][] = 'translade/transladecss';

            $form_entity = $form_state->getFormObject()->getEntity();
            $definitions = $form_entity->getFieldDefinitions();

            foreach ($definitions as $field_name => $def) {
                $field_type = $def->getType();
                if (in_array($field_type, get_supported_field_types())) {
                    // change class for js rendering
                    $form[$field_name]['#attributes']['class'][] = 'translade-field translade-type-' . $field_type;
                }
            }
        }
    }
}

/**
 * Returns an array of field types that are supported for translation.
 *
 * @return array
 *   An array of supported field types.
 */
function get_supported_field_types() {
    // Translade currently supports main text formats
    return [
        'string',
        'text',
        'text_long',
        'text_with_summary',
    ];
}

?>